### PR TITLE
Ch 10/write new content

### PR DESCRIPTION
**Pull request by restrellado**
Includes general review plus review for style. 

I tested the code and it runs. Still needs a code review for style and a grammar review.

### CODE REVIEW

**Comment by jrosen48** [comment]
Another minor code-related thing -- why do we have to quote 2012 here (can it not be treated as an integer)?

```
model_data %>%
  filter(year == "2012") %>%
  summary()
```

**Comment by jrosen48** [comment]
Very minor - are we using dataset or data set?

**Comment by jrosen48** [comment]
Are we avoiding contractions? Aren't, they're, etc.

I think so, but want to confirm.

**Comment by jrosen48** [comment]
Also, you'll, you're, here's

**Comment by restrellado** [comment]
> Minor -- should we consider using `purrr::pluck()` for this code?
> 
> https://purrr.tidyverse.org/reference/pluck.html
> 
> ```
> all_files[[5]]
> ```
> 
> What made me think of this was that we say, "Now that you know the 2016 dataset is the fifth element in the list, pluck it out by using double brackets"!

Deferring to code guru @ivelasq on this. No strong feelings from me either way. But I won't let the decision block the merge. Happy to open another PR if we decide to do it.

**Comment by restrellado** [comment]
> Very minor - are we using dataset or data set?

For both of these style questions, I posted in Slack to revisit. I'll merge and am happy to open another PR in case we need to make changes for either contractions or "dataset" vs "data set."

**Comment by restrellado** [comment]
> Another minor code-related thing -- why do we have to quote 2012 here (can it not be treated as an integer)?
> 
> ```
> model_data %>%
>   filter(year == "2012") %>%
>   summary()
> ```

We could probably remove. But I just checked and at that part of the walkthrough `year` is a factor. That's probably why I used quotes. That may be an outdated way of doing it—let me know if so. I'm going to merge as is, but happy to change if anyone has strong feelings.

**Pull request merged**
