### PR TITLE
Coordinate content between aggregate data (c9) and longitudinal data (c10) chapters

### PR DESCRIPTION
**Pull request by jrosen48**
@ivelasq @restrellado, in this PR, I worked on moving/modifying some of the content in the `# Background` section into `# Chapter Overview` sections. Something that arose in the course of creating these chapter overviews has to do with how we approach aggregate data in the two chapters. 

For c9,  here is the overview:

> A common situation encountered when searching for education data, particularly
by analysts who are not directly working with schools or districts, is the
prevalence of publicly available, *aggregate data*. Aggregate data refers to
numerical or non-numerical information that is (1) collected from multiple
sources and/or on multiple measures, variables, or individuals and (2) compiled
into data summaries or summary reports, typically for the purposes of public
reporting or statistical analysis [@greatschools2014]. Example of publicly
available aggregate data include school-level graduation rates, state test
proficiency scores by grade and subject, or mean survey responses. In this
walkthrough, we explore the role of aggregate data, with a focus on educational
equity, from a single school district.

For c10, here is the overview:

> Data scientists working in education don't always have access to student level
data, so knowing how to model publicly available datasets, as in [the previous
chapter](#c9), is a useful skill. This walkthrough builds upon and extends the
focus on aggregate data in the last chapter to focus on change over time in
students with disabilities in each state.

I am wondering how we can distinguish how we use aggregate data in c10 - or, if the techniques are *mostly* similar, whether we can state that c10 is distinguished not by its use of aggregate data, but on analyses of differences/changes over time. Thoughts on this? Thank you!

### CODE REVIEW

**Comment by restrellado** [comment]
I'm on it. Will review tonight and offer suggestions. Related: #338

**Comment by restrellado** [comment]
One way we can frame this is by moving part of the conclusion in c10 to the beginning of c9 as @ivelasq suggested in #338. 

In c9, say something like 

> Though aggregate data has its advantages and limitations, we wanted to spend a little more time with it since it's so commonly used in education. This chapter and chapter 10 provide two different examples of cleaning an aggregate dataset and two different examples of using aggregate datasets to compare student experiences. In this chapter, we'll identify and compare patterns in student race groups. In the next chapter, we'll compare student counts over time in different states. 

I'll go ahead and combine this issue with #338 to help us coordinate these two solutions.

**Comment by restrellado** [comment]
From @ivelasq in #338 

>@restrellado reading through - the end of Ch 10/Walkthrough 4 does a great job introducing aggregate data. Since Ch 9 is intro to aggregate data, thoughts of putting it in there instead? Specifically thinking of the paragraph beginning in "Before we discuss the benefits of aggregate data..." and moving it before 9.1.1.1.

**Comment by jrosen48** [comment]
> One way we can frame this is by moving part of the conclusion in c10 to the beginning of c9 as @ivelasq suggested in #338.
> 
> In c9, say something like
> 
> > Though aggregate data has its advantages and limitations, we wanted to spend a little more time with it since it's so commonly used in education. This chapter and chapter 10 provide two different examples of cleaning an aggregate dataset and two different examples of using aggregate datasets to compare student experiences. In this chapter, we'll identify and compare patterns in student race groups. In the next chapter, we'll compare student counts over time in different states.
> 
> I'll go ahead and combine this issue with #338 to help us coordinate these two solutions.

I like this framing a lot, and think this would be perfect to include at the beginning of c9!

**Comment by jrosen48** [comment]
TY!

**Pull request merged**
