### PR TITLE
initial commit for a companion walkthrough for walkthrough 7, on text analysis of tidytuesday

### PR DESCRIPTION
**Pull request by jrosen48**

### CODE REVIEW

**Comment by restrellado** [comment]
Should I create another chapter milestone for this one or should I added it to the TidyTuesday text analysis milestone?

**Comment by jrosen48** [comment]
I think a different one - I think the focus will be different enough. Is
that okay with you?

**Comment by jrosen48** [comment]
right now, this data does not contain any retweets (which is problematic for how I wrote this, which was originally for analyzing #AECT19 tweets for a workshop walkthrough), though if we search tidytuesday and augment the existing tweets with these, we should have enough to get started with this.

**Comment by jrosen48** [comment]
On the other hand, we could remove retweets - make this just about mentions - that may be clearer to readers.

**Comment by jrosen48** [comment]
this is now a rough draft ready for a review.

One comment and one question.

Comment: I think that Technical Appendix A should be moved to the text analysis walkthrough (discussed in #117). 

Question: Should Technical Appendix B remain? In terms of fitting the narrative, it, well, doesn't. But I really like this content (it is from awhile ago) and would love to emphasize this, somehow. Open to any ideas.

**Pull request merged**
