### PR TITLE
Reorder chapters

### PR DESCRIPTION
**Pull request by restrellado**
I left the random forest walkthrough alone, but after it's done we can change the name and it should slot right in no problem. @jrosen48 I didn't update `19-references.R` because I didn't want to mess with the biblio system. Let me know if I should update it and I'm happy to.

### CODE REVIEW

**Comment by jrosen48** [comment]
Thanks much. For that references doc, it is an empty chapter with a level-one heading (`# References`), after which references will be rendered.

Seems clunky, but [what bookdown seems to suggest](https://bookdown.org/yihui/bookdown/citations.html):

>  For non-LaTeX output, you can add an empty chapter as the last chapter of your book

So as long as that's the last chapter, we should be good to go.

**Comment by jrosen48** [comment]
just realized I missed a step with the empty references chapter. It also has to have the following line in it:

`r if (knitr::is_html_output()) '# References {-}'`

**Comment by restrellado** [comment]
> just realized I missed a step with the empty references chapter. It also has to have the following line in it:
> 
> `r if (knitr::is_html_output()) '# References {-}'`
> 
> Can revise that (was supposed to be addressed in #214) in a new PR. Should I number that `20-references.Rmd`?

No worries I'm in it right now. I'll add this

**Comment by restrellado** [comment]
All those changes created conflicts so I'm going to close this down and redo it. Should have it done today

**Pull request closed without merging**
