### PR TITLE
C15 c16 jmr edits

### PR DESCRIPTION
**Pull request by jrosen48**

### CODE REVIEW

**Comment by jrosen48** [comment]
Hi all, coming upon this comment in c16:

```
Differentiation is a method for providing multiple pathways for learners to engage with, understand, and ultimately apply new content and new skills. To differentiate this text, we first created personas for who we expected to be common groups of readers of the book (see @wilson2009 for an example). We then differentiate the book by recognizing and providing background content/skills (either explicitly or through reference to other resources), embedded checks for understanding, and recommendations for where to begin based upon prior expertise. We also provide screenshots that are annotated and reflective of the content in the text to help to show readers how they are able to use what they are reading about.

<!-- Say more about this - specifically how we use the user personas? -->
```

Can you all remind me/help me to add a few sentences on how we use the personas (from interviews)? 
 @jmostipak wondering if you're best equipped to helping with this? Related, perhaps we could use this to mention the self-evaluation system (#280).

**Comment by jrosen48** [comment]
@kierisi one more Q - could you help me to add ~2-3 sentences to the universal design section?

```
Universal design is a series of principles which guide the creation of spaces
that are inclusive and accessible to individuals from all walks of life
regardless of age, size, ability, or disability [@steinfeld2012]. While
traditionally applied to physical spaces, we have extended these principles to
the creation of this book in such a way that the text and accompanying materials
will be designed for individuals from all walks of life, regardless of
educational level, background, ability, or disability.

Many of the seven guiding principles of Universal Design are readily
transferable to the creation of a text, such as equitable use, flexibility in
use (aided in large part through differentiation), simple and intuitive use,
perceptible information, and tolerance for error.

<!-- Say more regarding how we apply these? -->

<!-- Also say how this can be applied more generally? -->
```

**Comment by kierisi** [comment]
re: first comment: @restrellado can jump in and provide more context as needed, as he did the bulk of the interviews! I think you've nailed it, though. perhaps modify it a bit to make it clear that instead of who we expect to be our readers, that we very clearly wanted to work with specific groups of readers, and conducted interviews with individuals in each user persona group to ensure that we were meeting the needs of each user group.

**Comment by kierisi** [comment]
re: comment 2 - we might need to strike this. I don't know if `bookdown` plays well with screenreaders, and I don't know that we've truly done anything to make the book accessible to users from diverse backgrounds. I'd be uncomfortable labeling our book as incorporating Universal Design at this stage.

**Comment by restrellado** [comment]
> re: comment 2 - we might need to strike this. I don't know if `bookdown` plays well with screenreaders, and I don't know that we've truly done anything to make the book accessible to users from diverse backgrounds. I'd be uncomfortable labeling our book as incorporating Universal Design at this stage.

I had the same thought also. I don't think we've included enough reviews for accessibility to feel great about saying this yet.

**Comment by restrellado** [comment]
> re: first comment: @restrellado can jump in and provide more context as needed, as he did the bulk of the interviews! I think you've nailed it, though. perhaps modify it a bit to make it clear that instead of who we expect to be our readers, that we very clearly wanted to work with specific groups of readers, and conducted interviews with individuals in each user persona group to ensure that we were meeting the needs of each user group.

Yep I think that's it! The personas were a way to imagine our audience and guide who we interviewed to prepare for the writing. Then the interviews equipped us to go beyond what we *imagined* the needs of our readers were and include their voices in the way we presented the content. The objective was for us to write in a way that helped the readers see themselves in the scenarios.

**Comment by jrosen48** [comment]
Thanks all. All sounds good. Will work on.

**Comment by jrosen48** [comment]
Hi all, wooh. Finally addressed this and am ready to merge. Thanks for weighing and for your contributions. @kierisi your comments on this when it was a draft provided a lot of fodder to improve it - thanks again.

**Pull request merged**
