### PR TITLE
Finalizing refs

### PR DESCRIPTION
**Pull request by jrosen48**

### CODE REVIEW

**Comment by jrosen48** [comment]
> A study by the Data Quality Campaign estimated that "95 percent of teachers use a combination of academic data (test scores, graduation rates, etc.) and nonacademic data (attendance, classroom, behavior, etc.) to understand their students' performance". 57 percent of the teachers in the study said a lack of time was a barrier to using the data they have. 

Is the following the write ref for this? 

> Nguyen, B. M. D., Nguyen, M. H., & Nguyen, T. L. K. (2013). Advancing the Asian American and Pacific Islander data quality campaign: Data disaggregation practice and policy. Asian American Policy Review, 24, 55.

```{code}
@article{nguyen2013advancing,
  title={Advancing the Asian American and Pacific Islander data quality campaign: Data disaggregation practice and policy},
  author={Nguyen, Bach-Mai Dolly and Nguyen, Mike Hoa and Nguyen, Tu-Lien Kim},
  journal={Asian American Policy Review},
  volume={24},
  pages={55},
  year={2013},
  publisher={Harvard Journal of African American Policy Studies}
}
```

**Comment by jrosen48** [comment]
Minor, do we have a page number for this direct quotation?

> In his book Feck Perfuction, designer @victore2019 writes "Success goes to those who keep moving, to those who can practice, make mistakes, fail, and still progress. It all adds up. Like exercise for muscles, the more you learn, the more you develop, and the stronger your skills become" (p. xx).

**Comment by jrosen48** [comment]
One more from this chapter:

> In 1990 Elizabeth Newton, then a Stanford University graduate, asked research subjects to "tap" out well-known songs with their fingers and estimate how many people would recognize the songs. She found that they overestimated every time!

**Comment by restrellado** [comment]
> > A study by the Data Quality Campaign estimated that "95 percent of teachers use a combination of academic data (test scores, graduation rates, etc.) and nonacademic data (attendance, classroom, behavior, etc.) to understand their students' performance". 57 percent of the teachers in the study said a lack of time was a barrier to using the data they have.
> 
> Is the following the write ref for this?
> 
> > Nguyen, B. M. D., Nguyen, M. H., & Nguyen, T. L. K. (2013). Advancing the Asian American and Pacific Islander data quality campaign: Data disaggregation practice and policy. Asian American Policy Review, 24, 55.
> 
> ```
> @article{nguyen2013advancing,
>   title={Advancing the Asian American and Pacific Islander data quality campaign: Data disaggregation practice and policy},
>   author={Nguyen, Bach-Mai Dolly and Nguyen, Mike Hoa and Nguyen, Tu-Lien Kim},
>   journal={Asian American Policy Review},
>   volume={24},
>   pages={55},
>   year={2013},
>   publisher={Harvard Journal of African American Policy Studies}
> }
> ```

I don't think that's the one. I found the information [on this web article](https://dataqualitycampaign.org/resource/teachers-see-the-power-of-data-but-dont-have-enough-time-to-use-it/). The [infographic](https://dataqualitycampaign.org/wp-content/uploads/2018/09/DQC_DataEmpowers-Infographic.pdf) says the data was from a Harris poll conducted in 5/23-5/28/18.

**Comment by restrellado** [comment]
> Minor, do we have a page number for this direct quotation?
> 
> > In his book Feck Perfuction, designer @victore2019 writes "Success goes to those who keep moving, to those who can practice, make mistakes, fail, and still progress. It all adds up. Like exercise for muscles, the more you learn, the more you develop, and the stronger your skills become" (p. xx).

Found it! It's on page 36.

**Comment by restrellado** [comment]
> "When I was a kid, there was no collaboration; it's you with a camera bossing your friend around. But as an adult, filmmaking is all about appreciating the talents of the people you surround yourself with and knowing you could never have made any of these films by yourself."

This one's a little harder. I just [googled it and found it](https://www.brainyquote.com/quotes/steven_spielberg_584073)–not sure what the primary source is.

**Comment by restrellado** [comment]
> In 1990 Elizabeth Newton, then a Stanford University graduate, asked research subjects to "tap" out well-known songs with their fingers and estimate how many people would recognize the songs. She found that they overestimated every time!

Got this one from the [Wikipedia page for the curse of knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge). Here's what they have for their sources on this: 

[https://hbr.org/2006/12/the-curse-of-knowledge](https://hbr.org/2006/12/the-curse-of-knowledge)
[https://creatorsvancouver.com/wp-content/uploads/2016/06/rocky-road-from-actions-to-intentions.pdf](https://creatorsvancouver.com/wp-content/uploads/2016/06/rocky-road-from-actions-to-intentions.pdf)

**Comment by restrellado** [comment]
Hey @jrosen48 I'm going to let you merge this one when you're ready. Not sure if you had more to do on it

**Comment by jrosen48** [comment]
thanks will try to finish today

**Comment by jrosen48** [comment]
#jewishchristmaseve

**Comment by jrosen48** [comment]
Just noting this - as a principle, if a book is freely-available, then I am keeping a link to it in-text (and citing a reference to it) - if not, I am only citing it (and adding a reference to it).

**Comment by jrosen48** [comment]
> > "When I was a kid, there was no collaboration; it's you with a camera bossing your friend around. But as an adult, filmmaking is all about appreciating the talents of the people you surround yourself with and knowing you could never have made any of these films by yourself."
> 
> This one's a little harder. I just [googled it and found it](https://www.brainyquote.com/quotes/steven_spielberg_584073)–not sure what the primary source is.

found it (I think)! NY Times [interview](https://carpetbagger.blogs.nytimes.com/2011/12/20/the-adventures-of-spielberg-an-interview/)?

**Comment by jrosen48** [comment]
another principle - only link to a source once (the first) time

**Comment by jrosen48** [comment]
Woohoo! merging

**Pull request merged**
