### PR TITLE
Updates to README

### PR DESCRIPTION
**Pull request by restrellado**
These are maintenance edits to bring the description up to date now that the book is published.

### CODE REVIEW

**Comment by restrellado** [comment]
@ivelasq there are some failed checks. They look like they're related to Netlify. Sorry! If it helps to know, my fork is up to date and I was working in a fresh clone of the fork.

**Comment by ivelasq** [comment]
@restrellado seems like the build we were using was out of date. Could you push a change, please? It doesn't seem to rerun the checks when I click "rerun".

**Comment by restrellado** [comment]
@ivelasq Ok just pushed a new change. Let me know if you need me to close this and try a separate PR.

**Review by ivelasq — APPROVED** [review]
Looks great! Thank you for editing!

**Comment by ivelasq** [comment]
@restrellado looks like the new build is working 👍

**Pull request merged**
